name: MinetopiaID
main: me.boykev.idbewijs.Main
author: boykev
website: https://www.boykevanvugt.nl
version: RELEASE-1
api-version: 1.12
api: "1.12"
depend: [NBTAPI]
commands:
  mtid:
    description: Main commando voor ID Bewijzen.
  debug:
    description: Debug command for boykev.
  minetopiaid:
    description: Main plugin command.